/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiStudioRouteImport } from './routes/ai-studio'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as QuestionBankRouteImport } from './routes/question-bank'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SyllabusRouteImport } from './routes/syllabus'
import { Route as ApiPublicDailyRemindersRouteImport } from './routes/api/public/daily-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudioRoute = AiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankRoute = QuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusRoute = SyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailyRemindersRoute = ApiPublicDailyRemindersRouteImport.update({
  id: '/api/public/daily-reminders',
  path: '/api/public/daily-reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/exams': typeof ExamsRoute
  '/notes': typeof NotesRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/question-bank': typeof QuestionBankRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/syllabus': typeof SyllabusRoute
  '/api/public/daily-reminders': typeof ApiPublicDailyRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/exams': typeof ExamsRoute
  '/notes': typeof NotesRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/question-bank': typeof QuestionBankRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/syllabus': typeof SyllabusRoute
  '/api/public/daily-reminders': typeof ApiPublicDailyRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/exams': typeof ExamsRoute
  '/notes': typeof NotesRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/question-bank': typeof QuestionBankRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/syllabus': typeof SyllabusRoute
  '/api/public/daily-reminders': typeof ApiPublicDailyRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-studio'
    | '/analytics'
    | '/auth'
    | '/exams'
    | '/notes'
    | '/plan'
    | '/practice'
    | '/question-bank'
    | '/scanner'
    | '/settings'
    | '/syllabus'
    | '/api/public/daily-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-studio'
    | '/analytics'
    | '/auth'
    | '/exams'
    | '/notes'
    | '/plan'
    | '/practice'
    | '/question-bank'
    | '/scanner'
    | '/settings'
    | '/syllabus'
    | '/api/public/daily-reminders'
  id:
    | '__root__'
    | '/'
    | '/ai-studio'
    | '/analytics'
    | '/auth'
    | '/exams'
    | '/notes'
    | '/plan'
    | '/practice'
    | '/question-bank'
    | '/scanner'
    | '/settings'
    | '/syllabus'
    | '/api/public/daily-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiStudioRoute: typeof AiStudioRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  ExamsRoute: typeof ExamsRoute
  NotesRoute: typeof NotesRoute
  PlanRoute: typeof PlanRoute
  PracticeRoute: typeof PracticeRoute
  QuestionBankRoute: typeof QuestionBankRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRoute
  SyllabusRoute: typeof SyllabusRoute
  ApiPublicDailyRemindersRoute: typeof ApiPublicDailyRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-studio': {
      id: '/ai-studio'
      path: '/ai-studio'
      fullPath: '/ai-studio'
      preLoaderRoute: typeof AiStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank': {
      id: '/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof QuestionBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus': {
      id: '/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof SyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-reminders': {
      id: '/api/public/daily-reminders'
      path: '/api/public/daily-reminders'
      fullPath: '/api/public/daily-reminders'
      preLoaderRoute: typeof ApiPublicDailyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiStudioRoute: AiStudioRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  ExamsRoute: ExamsRoute,
  NotesRoute: NotesRoute,
  PlanRoute: PlanRoute,
  PracticeRoute: PracticeRoute,
  QuestionBankRoute: QuestionBankRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRoute,
  SyllabusRoute: SyllabusRoute,
  ApiPublicDailyRemindersRoute: ApiPublicDailyRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
